### ISSUE TITLE
-b|--base64 arguments to print base64 encoded image data to stdout

### ISSUE THREAD

**Issue by JayBrown** [sindresorhus/file-icon-cli#4]
First of all… thank you *very* much for this fantastic little tool. Has already come in handy.

An idea: we already have a request for **[printing to stdout](https://github.com/sindresorhus/file-icon-cli/issues/1)**, and another related addition would be printing the image data to stdout as base64. Example:

`file-icon /Applications/foo.app --size 1024 -b > /tmp/foo_icon_1024_base64.txt`

**Comment by sindresorhus** [comment]
What's the use-case for needing it as `base64`?

And by the way, you can already do:

```sh
base64 <<< `file-icon /Applications/Safari.app --size 1024` > /tmp/foo_icon_1024_base64.txt
```

**Comment by JayBrown** [comment]
Ah, thank you for the tip. I will (for example) need the base64 functionality to ad-hoc print application icons in a menulet dropdown menu that's running in BitBar/xbar/SwiftBar.
