### ISSUE TITLE
Not able to generate icons for Apps that have space in their name

### ISSUE THREAD

**Issue by harish-sethuraman** [sindresorhus/file-icon-cli#5]
`file-icon /Applications/Visual Studio Code.app > vscode.png`

So I ran this command to generate VS code icon and I got

`Couldn't find: /Applications/Visual`

Probably it has something to do with those spaces. 

Do we have any other way of generating icon (like using - instead of space)?

**Comment by sindresorhus** [comment]
You need to quote the path or escape the space. This is about basic command-line handling and has nothing to do with this CLI specifically.
